inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

RSpec/ImplicitExpect:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Metrics/ClassLength:
  Max: 200
